# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7120adfb3c541814f0a3508d3ae4abda22f3198157bf27d234fb80571c21ec77191c976a749f1c66cc7ff509672f6d2043fba034cb87cbfbcd135734c301bb3

test:
  secret_key_base: 0d07f6310f2f7068484accd1ec7cfd53fcf449e0e847e7a7f97e088adc2dcce826d524029c7ebb9ee068a2a93c3ae782bc55e9b28440a8979cb0f00fa7025d7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
